# Generated by Django 5.2.8 on 2025-11-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_articleindexpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleindexpage',
            name='introduction',
        ),
    ]
