# Generated by Django 5.2.8 on 2025-11-18 10:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_articleindexpage_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'})}),
        ),
    ]
