# Generated by Django 5.2.8 on 2025-11-11 02:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 3), ('card_section', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'br'], 'help_text': 'Judul utama. Gunakan Shift+Enter untuk baris baru.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subjudul atau deskripsi singkat.', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Gambar latar belakang atau gambar utama.', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('hero_title', 0), ('hero_subtitle', 1), ('hero_image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Judul untuk seksi ini (misal: 'Profil Sekolah').", 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subjudul atau deskripsi untuk seksi ini (opsional).', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Gambar untuk kartu (opsional).', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Judul kartu.', 'max_length': 255, 'required': False}), 8: ('wagtail.blocks.TextBlock', (), {'help_text': 'Deskripsi singkat kartu.'}), 9: ('wagtail.blocks.StructBlock', [[('image', 6), ('title', 7), ('description', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('card', 9)]], {'use_json_field': True}), 11: ('wagtail.blocks.StructBlock', [[('title', 4), ('subtitle', 5), ('cards', 10)]], {})}, null=True),
        ),
    ]
