# Generated by Django 5.2.8 on 2025-11-12 01:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_section', 3), ('card_section', 11), ('maps_section', 15)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'br'], 'help_text': 'Judul utama. Gunakan Shift+Enter untuk baris baru.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subjudul atau deskripsi singkat.', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Gambar latar belakang atau gambar utama.', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('hero_title', 0), ('hero_subtitle', 1), ('hero_image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Judul untuk seksi ini (misal: 'Profil Sekolah').", 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subjudul atau deskripsi untuk seksi ini (opsional).', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Gambar untuk kartu (opsional).', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Judul kartu.', 'max_length': 255, 'required': False}), 8: ('wagtail.blocks.TextBlock', (), {'help_text': 'Deskripsi singkat kartu.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 6), ('title', 7), ('description', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('card', 9)]], {'required': False, 'use_json_field': True}), 11: ('wagtail.blocks.StructBlock', [[('title', 4), ('subtitle', 5), ('cards', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': "Judul Lokasi (misal: 'Lokasi Sekolah Kami')", 'max_length': 32, 'required': False}), 13: ('wagtail.blocks.TextBlock', (), {'help_text': "deskripsi text (misal: 'Temukan lokasi Sekolah kami dengan mudah dan cepat')", 'max_length': 64, 'required': False}), 14: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Tempat section untuk menaruh peta lokasi', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 12), ('subtitle', 13), ('element', 14)]], {})}, null=True),
        ),
    ]
