# Generated by Django 6.0 on 2026-01-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_chatbot', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
