# Generated by Django 5.2.8 on 2025-11-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0002_navigationsettings_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='show_children',
            field=models.BooleanField(default=False, help_text="Centang untuk menampilkan anak halaman dari 'link_page' sebagai dropdown."),
        ),
    ]
