# Generated by Django 5.2.8 on 2025-11-12 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0003_menuitem_show_children'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='site',
            field=models.OneToOneField(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='show_children',
            field=models.BooleanField(help_text="Centang untuk menampilkan anak halaman dari 'link_page' sebagai dropdown."),
        ),
    ]
