# Generated by Django 5.2.8 on 2025-11-13 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['title'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='A unique slug to identify this menu.', max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='open_in_new_tab',
            field=models.BooleanField(help_text='Open link in a new browser tab.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank to make this a top-level menu item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='navigation.menuitem'),
        ),
    ]
